version: '3'
services:
        web:
                image: flask_sport
                build: .
                ports:
                        - "8055:8080"
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/T8055_Sport/volumes
